In [2]:
import pandas as pd
import numpy as np 

pd.set_option('display.max_columns', None)

path = "../data/dataset.csv"

df = pd.read_csv(path)
print(df.shape)
df.head()

(48048, 17)

,datetime,nat_demand,T2M_toc,QV2M_toc,TQL_toc,W2M_toc,T2M_san,QV2M_san,TQL_san,W2M_san,T2M_dav,QV2M_dav,TQL_dav,W2M_dav,Holiday_ID,holiday,school
0,2015-01-03 01:00:00,970.3450,25.865259,0.018576,0.016174,21.850546,23.482446,0.017272,0.001855,10.328949,22.662134,0.016562,0.096100,5.364148,0,0,0
1,2015-01-03 02:00:00,912.1755,25.899255,0.018653,0.016418,22.166944,23.399255,0.017265,0.001327,10.681517,22.578943,0.016509,0.087646,5.572471,0,0,0
2,2015-01-03 03:00:00,900.2688,25.937280,0.018768,0.015480,22.454911,23.343530,0.017211,0.001428,10.874924,22.531030,0.016479,0.078735,5.871184,0,0,0
3,2015-01-03 04:00:00,889.9538,25.957544,0.018890,0.016273,22.110481,23.238794,0.017128,0.002599,10.518620,22.512231,0.016487,0.068390,5.883621,0,0,0
4,2015-01-03 05:00:00,893.6865,25.973840,0.018981,0.017281,21.186089,23.075403,0.017059,0.001729,9.733589,22.481653,0.016456,0.064362,5.611724,0,0,0

In [3]:
print(df.columns)
print(df.dtypes)
print(df.info())

Index(['datetime', 'nat_demand', 'T2M_toc', 'QV2M_toc', 'TQL_toc', 'W2M_toc',
       'T2M_san', 'QV2M_san', 'TQL_san', 'W2M_san', 'T2M_dav', 'QV2M_dav',
       'TQL_dav', 'W2M_dav', 'Holiday_ID', 'holiday', 'school'],
      dtype='object')
datetime       object
nat_demand    float64
T2M_toc       float64
QV2M_toc      float64
TQL_toc       float64
W2M_toc       float64
T2M_san       float64
QV2M_san      float64
TQL_san       float64
W2M_san       float64
T2M_dav       float64
QV2M_dav      float64
TQL_dav       float64
W2M_dav       float64
Holiday_ID      int64
holiday         int64
school          int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48048 entries, 0 to 48047
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    48048 non-null  object
 1   nat_demand  48048 non-null  float64
 2   T2M_toc     48048 non-null  float64
 3   QV2M_toc    48048 non-null  float64
 4   TQL_toc     48048 non-null  float64
 5   W2M_toc     48048 non-null  float64
 6   T2M_san     48048 non-null  float64
 7   QV2M_san    48048 non-null  float64
 8   TQL_san     48048 non-null  float64
 9   W2M_san     48048 non-null  float64
 10  T2M_dav     48048 non-null  float64
 11  QV2M_dav    48048 non-null  float64
 12  TQL_dav     48048 non-null  float64
 13  W2M_dav     48048 non-null  float64
 14  Holiday_ID  48048 non-null  int64
 15  holiday     48048 non-null  int64
 16  school      48048 non-null  int64
dtypes: float64(13), int64(3), object(1)
memory usage: 6.2+ MB
None

In [4]:
### Renaming columns 
column_map = {
    "datetime": "timestamp",
    "nat_demand": "load",
    "T2M_toc": "temperature",
    "QV2M_toc": "humidity",
    "WS10M_toc": "wind_speed",
    "PRECTOTCORR_toc": "precipitation"
}

for old, new in column_map.items():
    if old in df.columns:
        df = df.rename(columns={old: new})

In [5]:
df.head()

,timestamp,load,temperature,humidity,TQL_toc,W2M_toc,T2M_san,QV2M_san,TQL_san,W2M_san,T2M_dav,QV2M_dav,TQL_dav,W2M_dav,Holiday_ID,holiday,school
0,2015-01-03 01:00:00,970.3450,25.865259,0.018576,0.016174,21.850546,23.482446,0.017272,0.001855,10.328949,22.662134,0.016562,0.096100,5.364148,0,0,0
1,2015-01-03 02:00:00,912.1755,25.899255,0.018653,0.016418,22.166944,23.399255,0.017265,0.001327,10.681517,22.578943,0.016509,0.087646,5.572471,0,0,0
2,2015-01-03 03:00:00,900.2688,25.937280,0.018768,0.015480,22.454911,23.343530,0.017211,0.001428,10.874924,22.531030,0.016479,0.078735,5.871184,0,0,0
3,2015-01-03 04:00:00,889.9538,25.957544,0.018890,0.016273,22.110481,23.238794,0.017128,0.002599,10.518620,22.512231,0.016487,0.068390,5.883621,0,0,0
4,2015-01-03 05:00:00,893.6865,25.973840,0.018981,0.017281,21.186089,23.075403,0.017059,0.001729,9.733589,22.481653,0.016456,0.064362,5.611724,0,0,0

In [6]:
# Convert TImestamp and Sort 

df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values('timestamp')
df = df.reset_index(drop=True)

In [7]:
print(df['timestamp'].min())
print(df['timestamp'].max())

2015-01-03 01:00:00
2020-06-27 00:00:00

In [8]:
"""
The dataset spans from 
2015-01-03 01:00:00
2020-06-27 00:00:00
"""

'\nThe dataset spans from \n2015-01-03 01:00:00\n2020-06-27 00:00:00\n'

In [9]:
### Check for duplicate timestamps 
duplicates = df['timestamp'].duplicated().sum()
print(f"Number of duplicate timestamps: {duplicates}")

Number of duplicate timestamps: 0

In [10]:
# No duplicate timestamps found.

# Next important thing is to check for Missing time gaps 

expected = pd.date_range(
    start = df['timestamp'].min(),
    end = df['timestamp'].max(),
    freq = 'h'
)

missing_times = expected.difference(df['timestamp'])

print(f"Missing timestamps: {len(missing_times)} ")
missing_times[:10]

Missing timestamps: 0

DatetimeIndex([], dtype='datetime64[ns]', freq='h')

In [11]:
# There were no missing timestamps found either

missing = df.isnull().sum().sort_values(ascending=False)
missing_percent = (df.isnull().mean() * 100).sort_values(ascending=False)

pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_percent
})

             missing_count  missing_percent
timestamp                0              0.0
W2M_san                  0              0.0
holiday                  0              0.0
Holiday_ID               0              0.0
W2M_dav                  0              0.0
TQL_dav                  0              0.0
QV2M_dav                 0              0.0
T2M_dav                  0              0.0
TQL_san                  0              0.0
load                     0              0.0
QV2M_san                 0              0.0
T2M_san                  0              0.0
W2M_toc                  0              0.0
TQL_toc                  0              0.0
humidity                 0              0.0
temperature              0              0.0
school                   0              0.0

In [13]:
# There are no missing values in the dataset. We can move on normally now 

# lets convert the dataset to paraquet for faster loading in the future
df.to_parquet("../data/dataset.parquet", index=False)